const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('assert'),path=require('path');
const base=path.resolve(__dirname,'../dist');
const original=JSON.parse(fs.readFileSync(base+'/data/cells.json'));
const fixture=JSON.parse(JSON.stringify(original));fixture.cells=fixture.cells.slice(0,3);
fixture.cells.forEach((c,i)=>{c.capacity=5000;c.chargeMax=null;c.weight=70;c.stock=i===2?'unknown':'in_stock';c.discontinued=false;c.packSize=1;c.price=3;c.pricePack=3;c.priceTiers=[{minPacks:10,pricePack:2}];});
const dom=new JSDOM(fs.readFileSync(base+'/index.html','utf8'),{url:'https://wiki.example/sub/tools/cell-selector/',runScripts:'outside-only'}),w=dom.window;
let now=0,frames=new Map(),frameId=0,subscriptions=[],fetches=0;
w.performance.now=()=>now;w.requestAnimationFrame=cb=>{frames.set(++frameId,cb);return frameId};w.cancelAnimationFrame=id=>frames.delete(id);
w.matchMedia=()=>({matches:false});w.fetch=async()=>{fetches++;return {ok:true,json:async()=>JSON.parse(JSON.stringify(fixture))}};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
w.document$={subscribe:cb=>subscriptions.push(cb)};
const script=w.document.createElement('script');script.src='https://wiki.example/sub/assets/cell-selector/app.js';w.document.head.append(script);
Object.defineProperty(w.document,'currentScript',{value:script,configurable:true});
const code=fs.readFileSync(base+'/app.js','utf8').replace('return ()=>{lifetime.abort()',`root.test={setupSnapshot,visibleDomains,orderPrice,metric,get domains(){return displayDomains},get quantity(){return orderQuantity}};return ()=>{lifetime.abort()`);
w.eval(code);
const settle=()=>new Promise(resolve=>setTimeout(resolve,0));
const q=s=>w.document.querySelector(s);const input=(s,value)=>{q(s).value=value;q(s).dispatchEvent(new w.Event('input',{bubbles:true}))};
const tick=ms=>{now+=ms;const pending=[...frames.values()];frames.clear();pending.forEach(cb=>cb(now))};
(async()=>{
 await settle();const root=q('#fpv-nkon-tool');
 assert.equal(q('#cells').children.length,3);assert.equal(fetches,1);assert.equal(subscriptions.length,1);
 const api=root.test;assert(api.visibleDomains().capacity[1]>api.visibleDomains().capacity[0]);assert.deepEqual([...api.visibleDomains().chargeMax],[0,1]);
 assert(!/NaN|Infinity/.test(q('#radar').innerHTML));assert.equal(q('#unknown-stock').hidden,false);
 input('#purchaseQuantity',9);assert.equal(api.metric(fixture.cells[0],'price'),3);
 input('#purchaseQuantity',10);assert.equal(api.metric(fixture.cells[0],'price'),2);assert.equal(api.metric(fixture.cells[0],'whPerEuro'),fixture.cells[0].capacity/1000*fixture.cells[0].voltage/2);
 input('.range-filter[data-key="price"] input[data-edge="1"]',2.5);assert.equal(q('#cells').children.length,3);
 input('#purchaseQuantity',9);assert.equal(q('#cells').children.length,0);assert(q('#chartEmpty').hidden===false);
 q('#reset').click();q('[data-favorite="cell-001"]').click();q('[data-emphasize="cell-001"]').click();input('#search','no-matching-cell');
 assert.equal(q('#cells').children.length,0);assert.equal(q('#legend').children.length,1);assert.equal(q('#radar [data-shape]').getAttribute('stroke-width'),'3.3');
 assert(q('#radar [data-shape]').getAttribute('filter').includes('lineGlow'));
 q('#reset').click();input('#purchaseQuantity',10);tick(200);
 const intermediate=+q('#radar [data-domain="price"]').dataset.min;
 const point=q('#radar circle.point'),position=[point.getAttribute('cx'),point.getAttribute('cy')];
 input('#purchaseQuantity',1);assert.equal(+q('#radar [data-domain="price"]').dataset.min,intermediate,'Interrupted animation starts at current domain');
 assert.deepEqual([q('#radar circle.point').getAttribute('cx'),q('#radar circle.point').getAttribute('cy')],position,'Interrupted animation starts at current geometry');
 tick(700);assert.equal(q('#radar').dataset.animating,'false');assert(!/NaN|Infinity/.test(q('#radar').innerHTML));
 q('#axisBtn').click();q('[data-curve="capacity"]').value='high';q('[data-curve="capacity"]').dispatchEvent(new w.Event('change',{bubbles:true}));assert(!q('#curveNotice').hidden);
 w.matchMedia=()=>({matches:true});input('#purchaseQuantity',10);assert.equal(q('#radar').dataset.animating,'false');assert.equal(frames.size,0);
 const pack={price:3,pricePack:6,packSize:2,priceTiers:[{minPacks:10,pricePack:4}]};assert.equal(api.orderPrice(pack,18).unit,3);assert.equal(api.orderPrice(pack,19).unit,2);assert.equal(api.orderPrice(pack,20).cells,20);
 input('#search','BAK');const saved=w.localStorage.getItem('fpv-wiki:nkon:settings:v1');assert(saved.includes('BAK'));assert(saved.includes('high'));
 subscriptions.forEach(cb=>cb());assert.equal(fetches,1,'Repeated initialization must be idempotent');
 assert(q('#filterDialog').open,'Mobile axis controls open a live split view');assert.equal(w.document.body.style.overflow,'hidden');
 root.remove();subscriptions.forEach(cb=>cb());assert.equal(w.document.body.style.overflow,'','Navigation restores body scrolling');assert.equal(root.querySelectorAll('#radar').length,1,'Navigation restores the single chart');assert.equal(frames.size,0,'Animation canceled on navigation');
 w.document.body.append(root);subscriptions.forEach(cb=>cb());await settle();assert.equal(fetches,2);assert.equal(q('#purchaseQuantity').value,'10');assert.equal(q('#search').value,'BAK');assert.equal(q('[data-curve="capacity"]').value,'high');
 assert(w.localStorage.getItem('fpv-wiki:nkon:favorites:v1').includes('cell-001'));
 // A weak subset must keep headroom toward the complete database.
 const comparison=JSON.parse(JSON.stringify(fixture));comparison.cells.forEach((c,i)=>{c.name=i<2?'Weak '+i:'Strong';c.capacity=[1000,2000,6000][i];});
 root.test.setupSnapshot(comparison);input('#purchaseQuantity',1);input('#search','Weak');
 assert.equal(q('#cells').children.length,2);assert.equal(q('#scaleReference').value,'70');
 assert.deepEqual([...root.test.visibleDomains().capacity],[1000,4800]);
 assert((2000-1000)/(root.test.visibleDomains().capacity[1]-1000)<.3,'Weak best stays well below outer ring');
 input('#scaleReference',50);assert.deepEqual([...root.test.visibleDomains().capacity],[1000,4000]);
 input('#scaleReference',100);assert.deepEqual([...root.test.visibleDomains().capacity],[1000,6000]);
 input('#search','Strong');assert.deepEqual([...root.test.visibleDomains().capacity],[1000,6000],'Full database bounds stay fixed across filters');
 w.matchMedia=()=>({matches:false});input('#scaleReference',70);input('#search','Weak');tick(200);const between=+q('#radar [data-domain="capacity"]').dataset.max;
 input('#scaleReference',50);assert.equal(+q('#radar [data-domain="capacity"]').dataset.max,between);tick(700);
 input('#search','');q('[data-favorite="cell-003"]').click();input('#search','Weak');assert.equal(root.test.visibleDomains().capacity[1],6000,'Favorites contribute to the local bounds');
 assert.deepEqual([...root.test.visibleDomains().chargeMax],[0,1]);
 input('#scaleReference',100);comparison.cells[2].price=10;comparison.cells[2].pricePack=10;comparison.cells[2].priceTiers=[{minPacks:10,pricePack:1}];root.test.setupSnapshot(comparison);
 input('#purchaseQuantity',1);assert.deepEqual([...root.test.visibleDomains().price],[3,10]);input('#purchaseQuantity',10);assert.deepEqual([...root.test.visibleDomains().price],[1,2],'Database price reference uses effective tier prices');
 assert(JSON.parse(w.localStorage.getItem('fpv-wiki:nkon:settings:v1')).scaleReference===100);
 root.remove();subscriptions.forEach(cb=>cb());dom.window.close();
 console.log('PASS: quantities, pack tiers, price filter, missing/identical axes, interrupted animation, reduced motion, empty results, emphasis, settings, navigation lifecycle and database-anchored scale.');
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1});
